import type { Metadata } from "next";
import { Prompt, Poppins } from "next/font/google";
import GlobalStyle from "@/styles/GlobalStyles";
import StyledComponentsRegistry from "@/lib/registry";

const prompt = Prompt({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
  variable: "--font-prompt",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700", "800"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} ${poppins.variable}`}>
        <StyledComponentsRegistry>
          <GlobalStyle />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
